"""add brand and barcode_id to food_logs

Revision ID: 6527703f86f2
Revises: 94a69753acad
Create Date: 2026-05-13 10:06:05.411048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6527703f86f2'
down_revision = '94a69753acad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('barcode_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_column('barcode_id')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
