"""Add food models

Revision ID: 8d631de69406
Revises: 851f1e051e23
Create Date: 2026-04-02 00:04:04.644753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d631de69406'
down_revision = '851f1e051e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('protein_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('meal_type',
                existing_type=sa.VARCHAR(length=20),
                nullable=False)
        batch_op.create_index(batch_op.f('ix_food_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_logs_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('logged_at')
        batch_op.drop_column('quantity')
        batch_op.drop_column('food_id')
        batch_op.drop_column('notes')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('protein_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
                existing_type=sa.VARCHAR(length=100),
                type_=sa.String(length=120),
                existing_nullable=False)
        batch_op.alter_column('calories',
                existing_type=sa.FLOAT(),
                type_=sa.Integer(),
                existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_foods_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('foods_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('fat')
        batch_op.drop_column('protein')
        batch_op.drop_column('source')
        batch_op.drop_column('carbs')
        batch_op.drop_column('serving_size')
        batch_op.drop_column('fiber')
        batch_op.drop_column('serving_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serving_unit', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fiber', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('serving_size', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('fat', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('foods_user_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_foods_user_id'))
        batch_op.alter_column('calories',
                existing_type=sa.Integer(),
                type_=sa.FLOAT(),
                existing_nullable=False)
        batch_op.alter_column('name',
                existing_type=sa.String(length=120),
                type_=sa.VARCHAR(length=100),
                existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('fat_g')
        batch_op.drop_column('carbs_g')
        batch_op.drop_column('protein_g')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('food_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('logged_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'foods', ['food_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_food_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_logs_date'))
        batch_op.alter_column('meal_type',
                existing_type=sa.VARCHAR(length=20),
                nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('date')
        batch_op.drop_column('fat_g')
        batch_op.drop_column('carbs_g')
        batch_op.drop_column('protein_g')
        batch_op.drop_column('calories')
        batch_op.drop_column('food_name')

    # ### end Alembic commands ###
