"""add food brand barcode_id and food_log serving_size

Revision ID: 94a69753acad
Revises: dc378de5523e
Create Date: 2026-05-13 08:57:05.813361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a69753acad'
down_revision = 'dc378de5523e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serving_size', sa.String(length=100), nullable=True))

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('barcode_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('barcode_id')
        batch_op.drop_column('brand')

    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_column('serving_size')

    # ### end Alembic commands ###
