"""add food_id FK to food_logs

Revision ID: e65fa513a7b1
Revises: 6527703f86f2
Create Date: 2026-05-14 08:53:35.724819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65fa513a7b1'
down_revision = '6527703f86f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_food_logs_food_id'), ['food_id'], unique=False)
        batch_op.create_foreign_key('fk_food_logs_food_id', 'foods', ['food_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_food_logs_food_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_food_logs_food_id'))
        batch_op.drop_column('food_id')

    # ### end Alembic commands ###
